### ISSUE TITLE
What to do with the new travis.com plan?

### ISSUE THREAD

**Issue by sroet** [dwhswenson/contact_map#103]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

So the big point for us would be:
> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

So that seems they are giving a *one time* allotment of 1000 minutes (which would get us 67 nightly builds, at 15 min per build, and without you as a user running any other jobs) (The free plan explicitly says it does not replenish credits)

I found two options to go forward:
1) Apply for repeated open-source credits for this project
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:

   > Your account name and VCS provider (like travis-ci.com/github/[your account name] )
    How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat
    the process to  request more or discuss a renewable amount)

2) Switch to Azure for CI https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

@dwhswenson do you have any other options/ an opinion on which way to go forward? (No worries if you don't have time to figure out the switch, I might be able to spend a couple hours figuring that out)

Looking around it seems like Azure is getting more and more adaptation so I am +0.5 on that option but I am willing to default to your opinion here

**Comment by dwhswenson** [comment]
Ugh, this is going to be a pain. Long run, we may need to switch to Azure, but I'm not sure that Autorelease can maintain single-source for CI structure in that case. I'll have to look into it.

However, path 1 may be quite reasonable. I think we might request a renewable 10k credit (1000 minutes) allotment. If that's ~67 builds, it's a little more than we needed in October, but we were particularly busy in October. It will also encourage us to use a Travis cache to speed up build time, which would probably be a good thing anyway.

FWIW, here's what they are looking for to qualify as "open source" (per project):

1. You are a project lead or regular committer (latest commit in the last month)
2. Project must be at least 3 months old and is in active development (with regular commits and activity)
3. Project meets the OSD specification
4. Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
5. Project can not provide commercial services or distribute paid versions of the software

(from https://travis-ci.community/t/is-travis-educational-still-active-with-the-new-pricing-plan-how-to-enable-it/10456/4)

So we're solid on that here. It's a bit annoying for the various projects that aren't particularly active and just run a nightly build to check that nothing has broken (OPSPiggybacker, Autorelease, CodeModel). I'll probably move those over to Azure to get the feel for it (though they'll use their minutes slowly, since they have fast test suites and only run once/day.)

**Comment by sroet** [comment]
> but I'm not sure that Autorelease can maintain single-source for CI structure in that case. I'll have to look into it.

Shouldn't [this example](https://elanderson.net/2020/04/azure-devops-pipelines-use-yaml-across-repos/) solve most of your issues?

> I'll probably move those over to Azure to get the feel for it (though they'll use their minutes slowly, since they have fast test suites and only run once/day.)

Working on those as well, started with [Dask-traj](https://github.com/sroet/dask-traj) Which seems to be running on PRs and a nightly build and was not *too* painful to setup (took me 1 or 2 hours, most of which was getting familiar with the interface).
I still need to figure out: 
- How to get the coverage to report back to github, 
- How to *not* get an email for every completed build (now also getting the succesful ones)
- Find a new badge to display for the current build status

I will keep you updated on how those things go

**Comment by dwhswenson** [comment]
> Shouldn't this example solve most of your issues?

Looks likely! Thanks. I'm starting to play with Azure on a few projects as well. Once I get it running with Autorelease, we can make the switch here.

**Comment by dwhswenson** [comment]
Status update: https://github.com/dwhswenson/autorelease/issues/76
