### ISSUE TITLE
How to calculate the CA distance between two residues？

### ISSUE THREAD

**Issue by FYY99117** [dwhswenson/contact_map#125]
Besides，

According to the PDB file of a protein, we acquired the coordinate of the Ca
atom of each amino acid residue, and then calculated the Euclidean
distances between all residue pairs.

How to realize the above in contact_map?

**Comment by dwhswenson** [comment]
I'm not entirely sure I understand what you're aiming for. If you're looking for all of the Ca-Ca distances, it's probably best to directly use MDTraj (which Contact Map Explorer is built on) or something similar.

Contact Map Explorer is more efficient at finding contacts because it uses neighbor cells to find the nearest neighbors -- but that means that it only calculates distances for things that a good candidates for being within a given cutoff.

### All Ca-Ca distances

If you want to find all Ca-Ca distances for all residues using MDTraj, it would look something like this:


```python
import mdtraj as md
import itertools  # standard python package

pdb = md.load("kras.pdb")
carbon_alphas = pdb.topology.select("protein and name == 'CA'")

len(carbon_alphas)  # we should see 166 residues here
```




    166




```python
all_pairs = [pair for pair in itertools.combinations(carbon_alphas, 2)]
len(all_pairs) # == (166 * 165 / 2)  # scales as N**2
```




    13695




```python
distances = md.compute_distances(pdb, atom_pairs=all_pairs)
# we'll show the first 5 of the 13695 values calculated
for pair, dist in list(zip(all_pairs, distances[0]))[:5]:
    # this is a little fancy MDTraj to get the residue object
    residues = tuple(pdb.topology.atom(at).residue for at in pair)
    print(f"Distance between C-alphas for residues {residues}: {dist}")
```

    Distance between C-alphas for residues (MET1, THR2): 0.3816002905368805
    Distance between C-alphas for residues (MET1, GLU3): 0.6999122500419617
    Distance between C-alphas for residues (MET1, TYR4): 1.039697289466858
    Distance between C-alphas for residues (MET1, LYS5): 1.3857232332229614
    Distance between C-alphas for residues (MET1, LEU6): 1.623326301574707


### Ca-Ca distances for residues in contact

If you want to find Ca-Ca distances only for residues within contact distance (typically, Ca-based contacts are at 0.6 nm, whereas Contact Map Explorer defaults to heavy-atom contacts which are at 0.45 nm):


```python
import contact_map
contacts = contact_map.ContactFrequency(
    pdb,
    query=carbon_alphas,
    haystack=carbon_alphas,
    cutoff=0.6
)
pairs = [tuple(pair) for pair, count in contacts.atom_contacts.most_common_idx()]
len(pairs)  # scales with the number of contacts; roughly order of number of residues
```




    161




```python
distances = md.compute_distances(pdb, atom_pairs=pairs)
# we'll show the first 5 of the 161 values calculated
for pair, dist in list(zip(pairs, distances[0]))[:5]:
    residues = tuple(pdb.topology.atom(at).residue for at in pair)
    print(f"Distance between C-alphas for residues {residues}: {dist}")
```

    Distance between C-alphas for residues (ILE139, ALA134): 0.5190471410751343
    Distance between C-alphas for residues (ASP154, GLY151): 0.4983673393726349
    Distance between C-alphas for residues (PHE82, GLY115): 0.54787278175354
    Distance between C-alphas for residues (ALA83, ASN86): 0.5358847975730896
    Distance between C-alphas for residues (SER106, LYS101): 0.5714757442474365

Note that this will also give not count residues that are right next to each other (like 1 and 2) as neighbors, whereas the pure MDTraj version will.

---

The difference here is that when using Contact Map Explorer, you only look at the 161 pairs where the distance is less than 0.6 nm. Pure MDTraj gives you *all* 13695 pairs.

**Comment by FYY99117** [comment]
It was very helpful to me, thanks
