### ISSUE TITLE
Option to turn off topology compatibility check in `ContactDifference`

### ISSUE THREAD

**Issue by dwhswenson** [dwhswenson/contact_map#60]
Let's say I have a trajectory of a wild type protein and a trajectory of that protein with a point mutation. I might be interested in looking at the difference in the (residue) contact maps for these. The current code forbids it, because `ContactDifference` requires that topologies between the two contact frequencies be equal.

I think we can make this possible with the following:

1. Add a `check_topology` parameter to `ContactObject._check_compatibility` (defaults to `True`).

2. Add a `check_topology` parameter to `ContactDifference.__init__` (defaults to True). If `check_topology` is `False` and if `positive.topology != negative.topology`, then it will refuse to build the `atom_contacts`, but will build the `residue_contacts`.

The only way you'll be able to build this will be with `diff = ContactDifference(pos, neg, check_topology=False)` -- so a user has to really intend to do this for it to happen. But at least it is possible.

@sroet : Am I overlooking anything scientifically in this? Can you think of any reason that this wouldn't work?

The idea presented here would only work to compare trajectories with point mutations. I've been thinking about some "re-topologizing" functionality for MDTraj (e.g., breaking a single residue into parts). Including the possibility of inserting some empty residues would enable users to create meaningful contact map differences between different proteins, as long as they can create a sequence alignment.

**Comment by sroet** [comment]
>@sroet : Am I overlooking anything scientifically in this? Can you think of any reason that this wouldn't work?

Scientifically, not that I can think of

Programming wise: 

We do not keep track of the total number and which residues we include in the contactmap (which can be a subset of topology, due to query, haystack and cutoff), so that will have to be checked during the compare. (I suspect the query and haystack will also be different, so we have to skip those checks as well)

Also, functions like `most_common()` only carry one `object_f` which would mean that it will display the residue name of either `positive.topology` or  `negative.topology` even if the residue number is equal. Which may lead to unclear representing of data, as we do subtract the frequencies of the res_idx is equal, but then misrepresent it as only `RES-P` in the outputs.

**Comment by dwhswenson** [comment]
Good point. Maybe the best thing to do is to create a separate class for this. It would skip all checks related to the topology (topology itself and atom indices used in the code), and would have to internally create its own `topology` from the two, to provide labels (e.g., I think reporting the name as `GLN-62/LEU-62` would be clear to users).

**Comment by sroet** [comment]
(I thought I already commented on this, but apparently I did not)

>Good point. Maybe the best thing to do is to create a separate class for this. It would skip all checks related to the topology (topology itself and atom indices used in the code), and would have to internally create its own topology from the two, to provide labels (e.g., I think reporting the name as GLN-62/LEU-62 would be clear to users).

I am in favor of the separate class and the representation. 
I would still add a check to see if the number of residues is equal or ask the user to supply a `{resA:resB}` mapping `dict`

**Comment by sroet** [comment]
@dwhswenson was there anything left here that was not solved by #77 ?

**Comment by dwhswenson** [comment]
Nope; I think #77 resolved this.
