### ISSUE TITLE
UnboundLocalError: local variable 'unitcell_lengths' referenced before assignment

### ISSUE THREAD

**Issue by Jiaxing2018** [dwhswenson/contact_map#67]
I was trying to generate the contact frequency map using my .xtc and .pdb file. However, it has this error. I used the .xtc and .pdb files in the example and it works well. I don't know if there is anything wrong with my .xtc or .pdb file? Thank you for your help!

**Comment by Jiaxing2018** [comment]
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-15-34460bccab7f> in <module>
      8 
      9 
---> 10 trajectory_contacts = ContactFrequency(traj)
     11 
     12 # if you want to save this for later analysis

~/anaconda/envs/jupyter_notebook/lib/python3.6/site-packages/contact_map/contact_map.py in __init__(self, trajectory, query, haystack, cutoff, n_neighbors_ignored, frames)
    741                                                query, haystack, cutoff,
    742                                                n_neighbors_ignored)
--> 743         contacts = self._build_contact_map(trajectory)
    744         (self._atom_contacts, self._residue_contacts) = contacts
    745 

~/anaconda/envs/jupyter_notebook/lib/python3.6/site-packages/contact_map/contact_map.py in _build_contact_map(self, trajectory)
    777         residue_query_atom_idxs = self.residue_query_atom_idxs
    778 
--> 779         used_trajectory = self.slice_trajectory(trajectory)
    780         for frame_num in self.frames:
    781             frame_contacts = self.contact_map(used_trajectory, frame_num,

~/anaconda/envs/jupyter_notebook/lib/python3.6/site-packages/contact_map/contact_map.py in slice_trajectory(self, trajectory)
    585         if self.use_atom_slice and (len(self._all_atoms) <
    586                                     trajectory.topology.n_atoms):
--> 587             sliced_trajectory = _atom_slice(trajectory, self._all_atoms)
    588         else:
    589             sliced_trajectory = trajectory

~/anaconda/envs/jupyter_notebook/lib/python3.6/site-packages/contact_map/contact_map.py in _atom_slice(traj, indices)
     68     topology._numAtoms = len(indices)
     69     return md.Trajectory(xyz=xyz, topology=topology, time=time,
---> 70                          unitcell_lengths=unitcell_lengths,
     71                          unitcell_angles=unitcell_angles)
     72 

UnboundLocalError: local variable 'unitcell_lengths' referenced before assignment

**Comment by sroet** [comment]
Thank you for the raised issue.

This is a bug and has been fixed by #64. We however did not release a new version of our code to conda-forge after that. 

If you want you can use the latest version of the code by downloading the source code from git and running `pip install -e` from inside the main source code directory. Please let me know if this does not fix your issue

@dwhswenson what would be blocking a bug-fix release?

**Comment by dwhswenson** [comment]
> Thank you for the raised issue.

@Jiaxing2018 : Just repeating Sander's thanks for reporting the issue. We appreciate the bug report!

We'll do a release soon -- the pip-installable version will be up shortly after the release gets merged into our `stable` branch here; it may take a few hours to a day for it to become available on conda-forge. I'm traveling this weekend, but it will almost certainly be up by Monday.

> @dwhswenson what would be blocking a bug-fix release?

Me being lazy? (also: busy) 

Actually, the main issue is cognitive dissonance from:

1. All the PRs since 0.4.0 are minor changes/bugfixes, suggesting a 0.4.1 release
2. But we renamed to "Contact Map Explorer," which seems like it should come with a 0.5.0 release (even if that doesn't affect the code)

Here's the auto-generated change log:

* Move to Autorelease 0.1.0 (#66)
* Fix for lack of unitcell; better colorbar scaling (#64) @~nffaruk [edit: added tilde to not spam]
* Fix coveralls reporting (#63)
* Rename to Contact Map Explorer (#61)
* Add Python 3.7 support (#41)
* Added test for non_periodic systems (#65)

I lean toward releasing as 0.5.0 with no new major features or enhancements, since the name change is conceptually signficant (even if not significant in the code). Thoughts, @sroet?

**Comment by sroet** [comment]
> I lean toward releasing as 0.5.0 with no new major features or enhancements, since the name change is conceptually signficant (even if not significant in the code). Thoughts, @sroet?

+1 on the 0.5.0 release

**Comment by dwhswenson** [comment]
Wait, it's going to take a little longer to get the release done. Pandas just released their 1.0 (2 days ago) and it looks like they broke some of the sparse matrix stuff we were using (although, with any luck, they sped it up in the process.)

Relevant info: https://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating

Probably can't fix this tonight, but can fix it soon.

**Comment by Jiaxing2018** [comment]
Hi all, thank you so much for the immediate response. I downloaded the source code and reinstalled contact_map.  It works fine now. Thanks again!

**Comment by sroet** [comment]
Closing this issue as solved. If any other bugs become apparent, please open a new issue!
