### ISSUE TITLE
Contact Difference of two trajectories

### ISSUE THREAD

**Issue by PeptideSimulator01** [dwhswenson/contact_map#73]
Dear all,

Contact Map Explorer was recommended to me and so far I really like it! I am looking at two peptide trajectories. What I want to do next, but can't get done, is to compare two trajectories with ContactDifference. I created the two ContactFrequencies
```
trajectory_contacts2 = ContactFrequency(traj2, cutoff=0.55)
trajectory_contacts2 = ContactFrequency(traj2, cutoff=0.55)
```
, but, when I do ``` diff=ContactDifference(trajectory_contacts1, trajectory_contacts2)``` I get the error:
```
AssertionError: Incompatible ContactObjects:
        topology: <mdtraj.Topology with 1 chains, 15 residues, 258 atoms, 262 bonds> != <mdtraj.Topology with 1 chains, 15 residues, 239 atoms, 243 bonds>
```
which is true, the number of atoms is different, but the number of residue is the same.

My question is: Is there a way to substract them from another to generate a Difference plot?
If not, can I get the values of the contact map to do this manually?

Any help or hint is appreciated,
Thank you :)

**Comment by dwhswenson** [comment]
Glad to hear it's useful! This issue is something that @sroet and I discussed at one point, because it does make sense that someone might, for example, want to calculate the difference with a mutant.

However, `ContactDifference` also supports looking at contacts at the atom-atom level, which would be meaningless in this case. In particular, methods like `diff.most_common_atoms_for_residue` would give results, but they would have no interpretable meaning. That's why you see the error you see now.

I think the following will get what you want, though:

```python
trajectory_contacts1 = ContactFrequency(traj1, cutoff=0.55)
trajectory_contacts2 = ContactFrequency(traj2, cutoff=0.55)

residue_diff = trajectory_contacts1.residue_contacts
res_2 = trajectory_contacts2.residue_contacts
residue_diff._counter.subtract(res_2.counter)
# note the underscore before first `counter`; doesn't matter for second one
```

From there, I think `residue_diff` should act like what you wanted after `diff.residue_contacts`. You can use `residue_diff.plot`, `residue_diff.most_common`, `residue_diff.most_common_idx`, etc. [Note: I haven't tried that code myself, so let me know if you run into problems with it.]

It would probably make sense for us to make this more straightforward. @sroet : Any thoughts? I see the two most reasonable options being (1) add an `ignore_incompatibilities` parameter to `ContactDifference.__init__`; or (2) implement `ContactCount.__sub__`.

I think I'm leaning toward the first. One thing about the first approach is that it would also allow you to compare contact maps with different values of, e.g., cutoff. That might be interesting. On the other hand, it makes it possible to do complete nonsense (compare contact maps from completely unrelated systems), but I think if we add a "be sure you know what you're doing" warning in the docs, we can reduce the likelihood of user error. Using the `-` operator would always require compatibility.

**Comment by PeptideSimulator01** [comment]
@dwhswenson your suggestion worked absolutely fantastic! Well done.

**Comment by sroet** [comment]
There was a whole part here on how to do this, but @dwhswenson beat me to it..

It is the best solution (and works in my test)


Now to answer @dwhswenson :
I would also vote for an `ignore_incompatibilities` flag 


My answer did contain a bit to respond the second part of your question, so here it is:

you can also get the data out as:
A pandas Dataframe (this does not work with pandas >=1.0.0, as contact_map is not (yet) compatible)
```python
# Make a dataframe
df1 = trajectory_contacts1.residue_contacts.df
df2 = trajectory_contacts2.residue_contacts.df
# pandas DataFrames can be subtracted as well
diff = df1-df2 
```
A sparse matrix
```python
sm1 = trajectory_contacts1.residue_contacts.sparse_matrix
sm2 = trajectory_contacts2.residue_contacts.sparse_matrix
# Sparse matrices can be subtracted as well
diff = sm1-sm2 
```

**Comment by sroet** [comment]
Alright, @PeptideSimulator01. It took a while, but with #77 merged this should now be possible and more intuitive.
Please reopen if any of your issues remain.

**Comment by dwhswenson** [comment]
Example here: https://contact-map.readthedocs.io/en/latest/examples/nb/Comparing%20different%20structures.html

**Comment by PeptideSimulator01** [comment]
> Alright, @PeptideSimulator01. It took a while, but with #77 merged this should now be possible and more intuitive.
> Please reopen if any of your issues remain.

Thanks a lot @sroet and @dwhswenson  for making this more intuitive and easy to handle. Just had a quick look at the notebook and the added functions and I think this will be useful in many applications! Thanks for the work. Hope Contact Map Explorer will get more attention in the future.
