### ISSUE TITLE
Subplots for ContactFrequency

### ISSUE THREAD

**Issue by nffaruk** [dwhswenson/contact_map#78]
Hello again, how would we go about arranging the plots generated through the plot method of ContactCount for different trajectories as subplots? I've tried [this Stack answer](https://stackoverflow.com/a/46906599) without any luck. Perhaps there should be an option to provide an existing figure or axis object to the plotting method? Thank you,

**Comment by dwhswenson** [comment]
Using an approach similar to the StackOverflow post, I'm able to get at least part of the way there. The tricky part is understanding how `fig.add_subplot()` works. Both calls need to define the same shape (`2, 1`) and then they vary in the index (`1` or `2`).

```python
# running in the examples directory, with the KRas example downloaded. matplotlib 3.1.1
import contact_map
import mdtraj as md
import matplotlib.pyplot as plt

traj = md.load("5550217/kras.xtc", top="5550217/kras.pdb")
contact0 = contact_map.ContactMap(traj[0])
contact1 = contact_map.ContactFrequency(traj)

fig0, ax0 = contact0.residue_contacts.plot()
fig1, ax1 = contact1.residue_contacts.plot()

fig = plt.figure()

# dummies to get positions
subplot1 = fig.add_subplot(2, 1, 1)
subplot2 = fig.add_subplot(2, 1, 2)
# remove the empty axes
subplot1.remove()
subplot2.remove()

# add ax0
ax0.figure = fig
ax0.set_position(subplot1.get_position())
fig.add_axes(ax0)

# add ax1
ax1.figure = fig
ax1.set_position(subplot2.get_position())
fig.add_axes(ax1)

fig.savefig("two_maps.png")
```
![two_maps](https://user-images.githubusercontent.com/8178546/87311637-cbad1f00-c51f-11ea-8289-ca530ae25360.png)

Interestingly, in the notebook it looks like it cuts off the top and right edges, but `savefig` looks just fine.  It also seems like things like `tight_layout` don't work here.

Clearly, this is still missing the colorbar. I may look a little more into how to add that, but I think techniques based on [`GridSpec`](https://matplotlib.org/3.1.1/tutorials/intermediate/gridspec.html) may be useful here. Note that our colorbars are custom (enabling us to use half a divergent color scheme, so that you have the same color scheme whether you're looking at a `ContactFrequency` (values 0 to 1) or a `ContactDifference` (values -1 to 1), but the colorbar only shows the relevant part.) Therefore you, need to add the actual `Axes` object that is created, e.g., `fig0.axes[1]`.

I think it makes sense to have `ax` as an optional input to the function. We can still return the same (`fig = ax.figure`), but it adds more flexibility. Then, I think the desired way for things to work would be:

```python
fig, ax = plt.subplots()
fig, ax = residue_contacts.plot(ax=ax)  # adds colorbar; my example would have 2 separate colorbars
fig, ax = residue_contact.plot(ax=ax, with_colorbar=False)  # no colorbar, but user can add one to fig
```

Main challenge in adding an `ax` parameter is that it conflicts some with the `kwargs`, which are currently passed to `plt.subplots`. Giving both would be nonsense. That said, I think that's mainly intended for `Figure` properties (e.g., `dpi`), which can by the user starting with `fig, ax = plt.subplots(dpi=300)` before passing `ax` as an argument. Plus, there are `params` to subplots that I don't think we can handle (e.g., asking for a grid of subplots -- that will probably cause errors now). Also, we can still allow it, but issue an error if both `ax` and additional `kwargs` for `subplots` are given.

@sroet : Given that info, options are:

1. Leave as is; harder to make multiple plots in a single figure.
2. Add `ax` parameter, leave `kwargs` allowed and raise error if both are given.
3. Add `ax` parameter, deprecate `kwargs` and plan to remove.

Any opinion?

**Comment by sroet** [comment]
@dwhswenson I opted for a slightly different option in #79 which is: split out the actual axis plotting and allow users to call that if they desire. Let me know what you think of that solution

**Comment by dwhswenson** [comment]
I think that can also work. Allows both things. I'll continue conversation over there.
